name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push To Gitlab
        env:
          token: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config user.name "idimetrix"
          git config user.email "use-react-hook+idimetrix@users.noreply.github.com"
          git remote add mirror "https://oauth2:${token}@gitlab.com/idimetrix/use-react-hook.git"
          git push mirror master
